#!/bin/bash 

MASTER_HOST=10.0.0.51
SLAVE_HOST=10.0.0.165
MYSQL_ROOT_USER=root
MYSQL_ROOT_PASSWORD=root123
MYSQL_DATABASE=applicationdb
MYSQL_USER=applicationuser
MYSQL_USER_PASSWORD=application123

Q1="CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;"
Q2="GRANT ALL ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_USER_PASSWORD' WITH GRANT OPTION;"
Q3="GRANT ALL ON *.* TO '$MYSQL_ROOT_USER'@'$MASTER_HOST' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD' WITH GRANT OPTION;"
Q4="GRANT ALL ON *.* TO '$MYSQL_ROOT_USER'@'$SLAVE_HOST' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD' WITH GRANT OPTION;"
Q5="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}${Q4}${Q5}"

mysql -u$MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD -e "$SQL"

#confirmation message
echo "Created database $MYSQL_DATABASE and user $MYSQL_USER_PASSWORD"